apps/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "apps"
urlpatterns = [
    path("event/", include("event.urls")),
    path("", views.HomeView.as_view(), name="index"),
    path("login/", include("login.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

event/urls.py
from django.urls import path

from . import views


app_name = "event"

urlpatterns = [
    # 勉強
    path("study/", views.study, name="study"),
    path("kyouka_tuika", views.kyouka_henshuu, name="kyouka_henshuu"),
    path("kyouka", views.kyouka_tuika, name="kyouka_tuika"),
    path("kyouka_shoukyo/<int:event_id>", views.kyouka_shoukyo, name="kyouka_shoukyo"),
    path("study_save1/", views.study_save1, name="study_save1"),
    path("study_save2/", views.study_save2, name="study_save2"),
    path("study_shousai/<int:event_id>", views.study_shousai, name="study_shousai"),
    path("modoru_study/", views.modoru_study, name="modoru_study"),

    # 日記
    path("diary/", views.diary, name="diary"),
    path("diary_save", views.diary_save, name="diary_save"),
    path("diary_shousai/<int:event_id>", views.diary_shousai, name="diary_shousai"),
    path("modoru_diary/", views.modoru_diary, name="modoru_diary"),

    # 夢日記
    path("dd", views.dd, name="dd"),
    path("dd_save", views.dd_save, name="dd_save"),
    path("dd_shousai/<int:event_id>", views.dd_shousai, name="dd_shousai"),
    path("modoru_dd/", views.modoru_dd, name="modoru_dd"),

    # ダイエット
    path("diet1/", views.diet1, name="diet1"),
    path("diet2/", views.diet2, name="diet2"),
    path("diet_save", views.diet_save, name="diet_save"),
    path("diet_shousai/<int:event_id>", views.diet_shousai, name="diet_shousai"),
    path("modoru_diet/", views.modoru_diet, name="modoru_diet"),
    path("eat_save/", views.eat_save, name="eat_save"),
    path("eat_shousai/<int:e_id>", views.eat_shousai, name="eat_shousai"),

    # タバコ
    path("smoke/", views.smoke, name="smoke"),
    path("smoke_save", views.smoke_save, name="smoke_save"),
    path("smoke_shousai/<int:event_id>", views.smoke_shousai, name="smoke_shousai"),
    path("modoru_smoke/", views.modoru_smoke, name="modoru_smoke"),
]

event/models.py
from django.db import models
import datetime

class Study(models.Model):
    subject = models.CharField(max_length=200)
    time = models.TimeField(null=True, default="00:00")
    memo = models.CharField(max_length=500, default="記録なし")

    textbook_name = models.CharField(max_length=200, null=True, default="記録なし")
    peji1 = models.IntegerField(null=True, default=0)
    peji2 = models.IntegerField(null=True, default=0)
    created = models.DateTimeField(auto_now_add=True)


class kyouka(models.Model):
    kyouka = models.CharField(max_length=100)

    
class diary(models.Model):
    tenki1 = models.CharField(max_length=50, default="記録なし")
    tenki2 = models.CharField(max_length=50, default="記録なし")
    date = models.DateField(default=datetime.date.today)
    title = models.CharField(max_length=300, default="記録なし")
    text = models.CharField(max_length=1000, default="記録なし")
    hitokoto = models.CharField(max_length=100, default="記録なし")
    sonohoka = models.CharField(max_length=300, default="記録なし")


class dd(models.Model):
    date = models.DateField(default=datetime.date.today)
    jinbutu = models.CharField(max_length=400, default="記録なし")
    title = models.CharField(max_length=300, default="記録なし")
    text = models.CharField(max_length=1000, default="記録なし")
    kansou = models.CharField(max_length=1000, default="記録なし")


class smoke(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, default="記録なし")
    mg = models.IntegerField(default=0)
    honn = models.IntegerField(default=0)
    memo = models.CharField(max_length=500, default="記録なし")


class diet(models.Model):
    date = models.DateField(default=datetime.date.today)
    height = models.IntegerField(default=0)
    kg = models.IntegerField(default=0)
    bmi = models.CharField(max_length=100, default="計算できませんでした")

    play = models.CharField(max_length=100, null=True, default="記録なし")
    time = models.TimeField(null=True, default="00:00")



class eat(models.Model):
    date = models.DateField(default=datetime.date.today)
    morning = models.CharField(max_length=1000, default="記録なし")
    lunch = models.CharField(max_length=1000, default="記録なし")
    dinner = models.CharField(max_length=1000, default="記録なし")
    sonohoka = models.CharField(max_length=1000, default="記録なし")
    eat_time = models.TimeField(null=True, default="記録なし")

event/views.py
from django.shortcuts import render
from event import models
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.utils import timezone

# 勉強
def study(request):
    all_st = models.Study.objects.order_by("-id").all()
    all_kyouka = models.kyouka.objects.all()
    dct1 = {"all_st":all_st, "all_kyouka":all_kyouka}
    return render(request, "event/study.html", dct1)

def kyouka_henshuu(request):
    all_kyouka = models.kyouka.objects.all()
    dct = {"all_kyouka":all_kyouka}
    return render(request, "event/kyouka.html", dct)

def kyouka_shoukyo(request, event_id):
    event  = models.kyouka.objects.get(id=event_id)
    event.delete()
    return HttpResponseRedirect(reverse("event:kyouka_henshuu"))

def kyouka_tuika(request):
    kyouka = request.POST.get("text")
    if kyouka == "" or kyouka == None:
        return render(request, "event/kyouka.html")
    sv = models.kyouka(kyouka=kyouka)
    sv.save()
    return HttpResponseRedirect(reverse("event:kyouka_henshuu"))

def study_save1(request):
    s = request.POST.get("btoodtype")
    t_h = request.POST.get("hhh")
    t_m = request.POST.get("mmm")
    t  = t_h + ":" + t_m
    m = request.POST.get("memo")
    created = request.POST.get("kiroku")
    tb_name = None
    peji1 = None
    peji2 = None
    sv = models.Study(subject=s, time=t, memo=m, textbook_name=tb_name, peji1=peji1, peji2=peji2, created=created)
    sv.save()
    return HttpResponseRedirect(reverse("event:study"))

def study_save2(request):
    s = request.POST.get("btoodtype")
    tb_n = request.POST.get("textbook_name")
    peji1 = request.POST.get("peji1")
    peji2 = request.POST.get("peji2")
    m = request.POST.get("memo")
    c = request.POST.get("kiroku")
    if peji1 == "" :
        peji1 = 00
    if peji2 == "" :
        peji2 = 00
    time = None
    if tb_n == "" or tb_n == None:
        tb_n = "記録なし"
    sv = models.Study(subject=s, time=time, textbook_name=tb_n, peji1=peji1, peji2=peji2, memo=m, created=c)
    sv.save()
    return HttpResponseRedirect(reverse("event:study"))


def study_shousai(request, event_id):
    event = models.Study.objects.get(id=event_id)
    dct = {"event":event}
    return render(request, "event/study_shousai.html", dct)

def modoru_study(request):
    return HttpResponseRedirect(reverse("event:study"))

# 日記
def diary(request):
    all_di = models.diary.objects.order_by("-id").all()
    dct = {"all_di":all_di}
    return render(request, "event/diary.html", dct)

def diary_save(request):
    date = request.POST.get("date")
    tenki1 = request.POST.get("tenki1")
    tenki2 = request.POST.get("tenki2")
    title = request.POST.get("title")
    text = request.POST.get("text")
    hitokoto = request.POST.get("hitokoto")
    sonohoka = request.POST.get("sonohoka")
    if date == "" or date == None:
        date = datetime.date.today()
    sv = models.diary(tenki1=tenki1, tenki2=tenki2, date=date, title=title,text=text, hitokoto=hitokoto, sonohoka=sonohoka)
    sv.save()
    return HttpResponseRedirect(reverse("event:diary"))

def diary_shousai(request, event_id):
    event = models.diary.objects.get(id=event_id)
    dct = {"event":event}
    return render(request, "event/diary_shousai.html", dct)

def modoru_diary(request):
    return HttpResponseRedirect(reverse("event:diary"))


# 夢日記
def dd(request):
    all_dd = models.dd.objects.order_by("-id").all()
    dct = {"all_dd":all_dd}
    return render(request, "event/dream_diary.html", dct)

def dd_save(request):
    date = request.POST.get("date")
    title = request.POST.get("title")
    jinbutu = request.POST.get("jinbutu")
    text = request.POST.get("text")
    kansou = request.POST.get("kansou")
    if date == "" or date == None:
        date = datetime.date.today()
    sv = models.dd(date=date, title=title, jinbutu=jinbutu, text=text, kansou=kansou)
    sv.save()
    return HttpResponseRedirect(reverse("event:dd"))

def dd_shousai(request, event_id):
    event = models.dd.objects.get(id=event_id)
    jinbutu = event.jinbutu.split()
    dct = {"event":event, "jinbutu":jinbutu}
    return render(request, "event/dream_diary_shousai.html", dct)

def modoru_dd(request):
    return HttpResponseRedirect(reverse("event:dd"))

# タバコ
def smoke(request):
    all_sm = models.smoke.objects.order_by("-id").all()
    dct = {"all_sm":all_sm}
    return render(request, "event/smoke.html", dct)

def smoke_save(request):
    date = datetime.date.today()
    name = request.POST.get("name")
    mg = request.POST.get("mg")
    honn = request.POST.get("honn")
    memo = request.POST.get("memo")
    sv = models.smoke(date=date, name=name, mg=mg, honn=honn, memo=memo)
    sv.save()
    return HttpResponseRedirect(reverse("event:smoke"))

def smoke_shousai(request, event_id):
    event = models.smoke.objects.get(id=event_id)
    dct = {"event":event}
    return render(request, "event/smoke_shousai.html", dct)

def modoru_smoke(request):
    return HttpResponseRedirect(reverse("event:smoke"))


# ダイエット
def diet1(request):
    all_dt = models.diet.objects.order_by("-id").all()
    dct = {"all_dt":all_dt}
    return render(request, "event/diet1.html", dct)

def diet2(request):
    all_eat = models.eat.objects.order_by("-id").all()
    dct = {"all_eat":all_eat}
    return render(request, "event/diet2.html", dct)

def diet_save(request):
    date = request.POST.get("date")
    height = request.POST.get("height")
    kg = request.POST.get("kg")
    play = request.POST.get("play")
    t_h = request.POST.get("hhh")
    t_m = request.POST.get("mmm")
    t  = t_h + ":" + t_m
    t_m = request.POST.get("mmm")
    t  = t_h + ":" + t_m
    if date == "" or date == None:
        date = datetime.date.today()

    if height == "" or height == None or kg == "" or kg == None :
        height = 0
        kg = 0
        bmi = "計測できませんでした"
    else:
        height = int(height)
        kg = int(kg)
        h = float(height / 100) ** 2
        bmi = kg / h
        bmi = round(bmi, 2)
    sv = models.diet(date=date, height=height, kg=kg, bmi=bmi, play=play, time=t)
    sv.save()
    return HttpResponseRedirect(reverse("event:diet1"))

def diet_shousai(request, event_id):
    event = models.diet.objects.get(id=event_id)
    dct = {"event":event}
    return render(request, "event/diet_shousai.html", dct)

def modoru_diet(request):
    return HttpResponseRedirect(reverse("event:diet1"))


def eat_save(request):
    eat = request.POST.get("eat")
    eat_time = request.POST.get("eat_time")
    eating = request.POST.get("eating")
    if eat_time == "" or None:
        eat_time = timezone.localtime()
    if eat == "朝ごはん":
        sv = models.eat(morning=eating, eat_time=eat_time)
    elif eat == "昼ごはん":
        sv = models.eat(lunch=eating, eat_time=eat_time)
    elif eat == "夜ごはん":
        sv = models.eat(dinner=eating, eat_time=eat_time)
    elif eat == "そのほか":
        sv = models.eat(sonohoka=eating, eat_time=eat_time)
    sv.save()
    return HttpResponseRedirect(reverse("event:diet2"))

def eat_shousai(request, e_id):
    event = models.eat.objects.get(id=e_id)
    dct = {"event":event}
    return render(request, "event/eat_shousai.html", dct)

event/templates/event/diet.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ダイエット記録</title>
    <link rel="stylesheet" href="{% static 'event/diet.css' %}">
</head>
<body>
    <div class="content">
        <div class="contents">
            <h2>今までの記録</h2>
            <div class="cont1">
                {% for event in all_dt %}
                {% if event.play == "" or event.play == None %}
                    <a href="{% url 'event:diet_shousai' event.id %}"><p>{{ event.date|date:"m/d" }} 運動名：記録なし</p></a>
                {% else %}
                    <a href="{% url 'event:diet_shousai' event.id %}"><p>{{ event.date|date:"m/d" }} 運動名：{{ event.play }}</p></a>
                    <hr>
                {% endif %}
                {% endfor %}
                <hr>
            </div>
            <div class="cont2">
                {% for e in all_eat %}
                {% if e.lunch == "" and e.dinner == "" and e.sonohoka == "" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　朝ごはん</p></a>
                {% elif e.morning == "" and e.dinner == "" and e.sonohoka == "" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　昼ごはん</p></a>
                {% elif e.lunch == "" and e.morning == "" and e.sonohoka == "" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　夜ごはん</p></a>
                {% elif e.lunch == "" and e.morning == "" and e.dinner == "" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　その他の食事</p></a>
                {% endif %}
                    <hr>
                {% endfor %}
            </div>
        </div>
        <div class="cont3">
            <h2>記録をつける</h2>
            <form method="post" action="{% url 'event:diet_save' %}">
                {% csrf_token %}
                <span>日付：</span>
                <input type="date" class="date" name="date">
                <span>身長：</span>
                <input type="number" class="num" name="height"><span>cm</span>
                <span>体重：</span>
                <input type="number" class="num" name="kg"><span>kg</span>
                <span>年齢：</span>
                <input type="number"  class="num"name="age">
                <br>
                <span>運動名：</span>
                <input type="text" placeholder="ランニング" class="text" name="play">
                <span>運動時間：</span>
                <input type="number" class="num" value="00" min="0" max="99" name="hhh">時間
                <input type="number" class="num" value="00" min="0" max="59" name="mmm">分
                <input type="submit" class="kiroku" value="記録をつける" name="botton">
            </form>
            <hr>
            <form method="post" action="{% url 'event:eat_save' %}">
                {% csrf_token %}
                <p>食べたものを記録しよう</p>
                <select name="eat">
                    <option value="朝ごはん">朝ごはん</option>
                    <option value="昼ごはん">昼ごはん</option>
                    <option value="夜ごはん">夜ごはん</option>
                    <option value="そのほか">そのほか</option>
                </select>
                <span>食べた時間</span>
                <input type="time" class="time" placeholder="00:00" name="eat_time">
                <span>食べたもの</span>
                <textarea placeholder="食べたものを改行区切りで書こう" name="eating"></textarea>
                <input type="submit" class="kiroku" value="記録をつける" name="botton2">
            </form>
        </div>
    </div>
</body>
</html>
{% endblock %}

event/templates/event/diet1.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ダイエット記録</title>
    <link rel="stylesheet" href="{% static 'event/diet.css' %}">
</head>
<body>
    <div class="content">
        <div class="contents">
            <div class="a">
            <h2>今までの運動記録</h2>
            <form action="{% url 'event:diet2'%}">
                {% csrf_token %}
                <input type="submit" value="食べた記録を表示" class="bbb">
            </form>
            </div>
            <div class="cont1">
                {% for event in all_dt %}
                {% if event.play == "" or event.play == None %}
                    <a href="{% url 'event:diet_shousai' event.id %}"><p>{{ event.date|date:"m/d" }} 運動名：記録なし</p></a>
                    <hr>
                {% else %}
                    <a href="{% url 'event:diet_shousai' event.id %}"><p>{{ event.date|date:"m/d" }} 運動名：{{ event.play }}</p></a>
                    <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="cont3">
            <h2>記録をつける</h2>
            <br>
            <div class="kiroku">
                <form method="post" action="{% url 'event:diet_save' %}">
                    {% csrf_token %}
                    <h4>運動記録</h4>
                    <span>日付：</span>
                    <input type="date" class="date" name="date">
                    <br>
                    <div class="tka">
                        <span>身長：</span>
                        <input type="number" class="num" name="height"><span>cm</span>
                        <span>体重：</span>
                        <input type="number" class="num" name="kg"><span>kg</span>
                    </div>
                    <br>
                    <span>運動名：</span>
                    <input type="text" placeholder="ランニング" class="text" name="play">
                    <span>運動時間：</span>
                    <input type="number" class="num" value="00" min="0" max="99" name="hhh">時間
                    <input type="number" class="num" value="00" min="0" max="59" name="mmm">分
                    <input type="submit" class="kiroku" value="記録をつける" name="botton">
                </form>
                <div class="eat">
                    <form method="post" action="{% url 'event:eat_save' %}">
                        {% csrf_token %}
                        <h4>食べた記録</h4>
                        <select name="eat">
                            <option value="朝ごはん">朝ごはん</option>
                            <option value="昼ごはん">昼ごはん</option>
                            <option value="夜ごはん">夜ごはん</option>
                            <option value="そのほか">そのほか</option>
                        </select>
                        <span>食べた時間</span>
                        <input type="time" class="time" placeholder="00:00" name="eat_time">
                        <br>
                        <textarea placeholder="食べたものを改行区切りで書こう" name="eating"></textarea>
                        <input type="submit" class="kiroku" value="記録をつける" name="botton2">
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

event/templates/event/diet2.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ダイエット記録</title>
    <link rel="stylesheet" href="{% static 'event/diet.css' %}">
</head>
<body>
    <div class="content">
        <div class="contents">
            <div class="a">
            <h2>今までの食べた記録</h2>
            <form action="{% url 'event:diet1'%}">
                {% csrf_token %}
                <input type="submit" value="運動記録を表示" class="bbb">
            </form>
            </div>
            <div class="cont2">
                {% for e in all_eat %}
                {% if e.lunch == "記録なし" and e.dinner == "記録なし" and e.sonohoka == "記録なし" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　朝ごはん</p></a>
                {% elif e.morning == "記録なし" and e.dinner == "記録なし" and e.sonohoka == "記録なし" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　昼ごはん</p></a>
                {% elif e.lunch == "記録なし" and e.morning == "記録なし" and e.sonohoka == "記録なし" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　夜ごはん</p></a>
                {% elif e.lunch == "記録なし" and e.morning == "記録なし" and e.dinner == "記録なし" %}
                    <a href="{% url 'event:eat_shousai' e.id %}"><p>{{ e.date|date:"m/d" }}　その他の食事</p></a>
                {% endif %}
                    <hr>
                {% endfor %}
            </div>
        </div>
        <div class="cont3">
            <h2>記録をつける</h2>
            <br>
            <div class="kiroku">
                <form method="post" action="{% url 'event:diet_save' %}">
                    {% csrf_token %}
                    <h4>運動記録</h4>
                    <span>日付：</span>
                    <input type="date" class="date" name="date">
                    <br>
                    <div class="tka">
                        <span>身長：</span>
                        <input type="number" class="num" name="height"><span>cm</span>
                        <span>体重：</span>
                        <input type="number" class="num" name="kg"><span>kg</span>
                    </div>
                    <br>
                    <span>運動名：</span>
                    <input type="text" placeholder="ランニング" class="text" name="play">
                    <span>運動時間：</span>
                    <input type="number" class="num" value="00" min="0" max="99" name="hhh">時間
                    <input type="number" class="num" value="00" min="0" max="59" name="mmm">分
                    <input type="submit" class="kiroku" value="記録をつける" name="botton">
                </form>
                <div class="eat">
                    <form method="post" action="{% url 'event:eat_save' %}">
                        {% csrf_token %}
                        <h4>食べた記録</h4>
                        <select name="eat">
                            <option value="朝ごはん">朝ごはん</option>
                            <option value="昼ごはん">昼ごはん</option>
                            <option value="夜ごはん">夜ごはん</option>
                            <option value="そのほか">そのほか</option>
                        </select>
                        <span>食べた時間</span>
                        <input type="time" class="time" placeholder="00:00" name="eat_time">
                        <br>
                        <textarea placeholder="食べたものを改行区切りで書こう" name="eating"></textarea>
                        <input type="submit" class="kiroku" value="記録をつける" name="botton2">
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

event/templates/event/kyouka.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'event/kyouka.css' %}">
</head>
<body>
    <form method="post" action="{% url 'event:kyouka_tuika' %}">
        {% csrf_token %}
        <input type="text" name="text" class="kyoukamei" placeholder="教科名">
        <input type="submit" class="tuika" name="submit" value="追加する">
    </form>
    <ul>
    {% for d in all_kyouka %}
    <form method="post" action="{% url 'event:kyouka_shoukyo' d.id %}">
        {% csrf_token %}
        <div class="kyouka">
            <li>{{ d.kyouka }}</li>
            <input type="submit" value="消去">
        </div>
    </form>
    {% endfor %}
    </ul>
    <form action="{% url 'event:modoru_study' %}" method="post">
        {% csrf_token %}
        <input type="submit" class="kirokuhe" value="記録へ" name="modoru">
    </form>
</body>
</html>
{% endblock %}

event/templates/event/smoke.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>タバコ記録</title>
    <link rel="stylesheet" href="{% static 'event/smoke.css' %}">
</head>
<body>
    <div class="content">
        <div class="cont1">
            <h3>今までの記録</h3>
            {% for event in all_sm %}
            <a href="{% url 'event:smoke_shousai' event.id %}"><p>{{ event.date|date:"m/d" }}　{{ event.name }}　{{ event.honn }}本</p></a>
            <hr>
            {% endfor %}
        </div>
        <div class="cont2">
            <div class="kiroku">
                <h3>記録する</h3>
                <form method="post" action="{% url 'event:smoke_save' %}">
                    {% csrf_token%}
                    <input type="text" class="text" placeholder="タバコ名" name="name">
                    <input type="number" class="num" value="00" min="0" name="mg">mg
                    <input type="number" class="num" value="00" min="0" name="honn">本
                    <textarea placeholder="メモ・ひとこと" name="memo"></textarea>
                    <input type="submit" value="記録する" class="kiroku" name="kiroku">
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

event/templates/event/study.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>勉強記録</title>
    <link rel="stylesheet" href="{% static 'event/study.css' %}">
</head>
<body>
    <div class="content">
        <div class="cont1">
            <h1>勉強記録</h1>
            {% for event in all_st %}
            {% if event.time == None %}
                <a href="{% url 'event:study_shousai' event.id %}"><p><p>{{ event.created|date:"m/d" }}　{{ event.subject }}　{{ event.peji1 }}ページ ~ {{ event.peji2 }}ページ</p></a>
                <hr>
            {% else %}
                <a href="{% url 'event:study_shousai' event.id %}"><p>{{ event.created|date:"m/d" }}　{{ event.subject }}　{{ event.time|time:"G時間i分" }}</p></a>
                <hr>
            {% endif %}
            {% endfor %}
        </div>
        <div class="cont2">
            <h1>記録する</h1>
            <form method="post" action="{% url 'event:kyouka_henshuu' %}">
                {% csrf_token %}
                <input type="submit" class="tuikabotan" name="kyouka_tuika" value="教科を編集">
            </form>
            <div class="kiroku">
            <div class="time">
                <h3>時間で記録する</h3>
                <form method="post" action="{% url 'event:study_save1' %}">
                    {% csrf_token%}
                    <select name="btoodtype">
                        <option value="なし">なし</option>
                        {% for k in all_kyouka %}
                        <option>{{ k.kyouka }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <input type="number" class="number" value="00" min="0" max="99" name="hhh">時間
                    <input type="number" class="number" value="00" min="0" max="59" name="mmm">分
                    <br>
                    <textarea placeholder="メモ・ひとこと" name="memo"></textarea>
                    <input type="submit" class="kiroku" value="記録する" name="kiroku">
                </form>
            </div>
            <hr>
            <div class="peji">
                <h3>ページ数で記録する</h3>
                <form method="post" action="{% url 'event:study_save2' %}">
                    {% csrf_token%}
                    <br>
                    <select name="btoodtype">
                        <option value="なし">なし</option>
                        {% for k in all_kyouka %}
                        <option>{{ k.kyouka }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <input type="text" class="text" placeholder="参考書名" name="textbook_name">
                    <input type="number" class="number" value="00" min="0" max="10000" name="peji1">ページ ~ 
                    <input type="number" class="number" value="00" min="0" max="10000" name="peji2">ページ
                    <br>
                    <textarea placeholder="メモ・ひとこと" name="memo"></textarea>
                    <input type="submit" class="kiroku" value="記録する" name="kiroku">
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}