apps/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "apps"
urlpatterns = [
    path("event/", include("event.urls")),
    path("", views.HomeView.as_view(), name="index"),
    path("login/", include("login.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.urls import path


from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from . import views

app_name = "login"
urlpatterns = [
    path(
        "", LoginView.as_view(template_name="login.html", next_page="/"), name="login"
    ),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("change-password/", PasswordChangeView.as_view(), name="change-password"),
    path("signup/", views.signup, name="signup"),
    path("study/", views.study, name="study"),
    path("diary/", views.diary, name="diary"),
    path("dd/", views.dd, name="dd"),
    path("diet/", views.diet, name="diet"),
    path("smoke/", views.smoke, name="smoke"),
]

templates/base.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>{% block title %}Board{% endblock %}</title>
</head>

<body>
    <nav class="py-2 bg-body-tertiary border-bottom">
        <div class="d-flex flex-wrap">
            <a href="{% url 'index' %}"
                class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none ms-3">
                <img src="{% static 'logo.png' %}"  class="bi me-2" width="40" height="32" role="img"></img>
            </a>
            <a href="{% url 'index' %}"
                class="nav d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <span class="fs-4">{{ title }}</span>
            </a>
            <ul class="nav me-auto">
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link link-body-emphasis px-2 active"
                        aria-current="page">Homeに移動</a></li>
            </ul>
            {% if user.is_authenticated %}
            <div class="nav d-block flex-shrink-0 dropdown">
                <a href="#" class="nav-link link-body-emphasis px-2 text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Hello, {{ user.username }}!
                </a>
                <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="{% url 'login:change-password' %}">Change password</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        <form action="{% url 'login:logout' %}" method="post">
                            {% csrf_token %}
                            <a href="javascript:void(0)" onclick="this.parentNode.submit()"
                                class="dropdown-item">Logout</a>
                        </form>
                    </li>
                </ul>
            </div>
            
            {% else %}

            <ul class="nav">
                <li class="nav-item d-flex">
                    <span class="d-flex align-items-center ">Hello, Guest!</span>
                </li>
                <li class="nav-item border-bottom"><a href="{% url 'login:login' %}"
                        class="nav-link link-body-emphasis px-2">Login</a>
                </li>
                <li class="nav-item border-bottom">
                    <a href="{% url 'login:signup' %}" class="nav-link link-body-emphasis px-2">Sign
                        up</a>
                </li>
            </ul>
                {% endif %}
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block title %}
Board | Home
{% endblock %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>いろいろ記録</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="ccc">
        <h1>記録をつけたいものを選ぼう</h1>
    <div class="button">
        <form action="{% url 'login:study' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="勉強">
        </form>
        <form action="{% url 'login:smoke' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="タバコ">
        </form>
        <form action="{% url 'login:diet' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="ダイエット">
        </form>
        <form action="{% url 'login:diary' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="日記">
        </form>
        <form action="{% url 'login:dd' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="夢日記">
        </form>
    </div>
</div>

</body>
</html>
{% endblock %}